### ISSUE TITLE
Upgrade 5.8 to 6

### ISSUE THREAD

**Issue by mozvatic** [rappasoft/laravel-boilerplate#1287]
Is posible to upgrade boilerplate 5.8 to 6?

I create my CMS with boilerplate 5.8, but have problem if i wanna upgrade laravel to 6

tnx

**Comment by bryanrscott** [comment]
Ive done a few updates between versions.   I generally base off a fresh copy of laravel boilerplate.  It is not so bad if you structure your code in seperate folders (eg /app/Models/<MyModule> . and /app/Http/Frontend/<MyModule>) as these mostly just copy across.

Some times the version update means you need to edit a bit the standard code.   For example in 5.8 to 6.0 the repositories need updating because of the change in the way the class file is specified.   Just look to the examples provided with laravel boilerplate in auth examples.

If you were using a feature like auditing where the package swapped then you need to either include the additional package or swap you usage

Bryan
