### ISSUE TITLE
LB 7.0

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-boilerplate#1323]
There's a reason it seems I haven't been maintaining this project recently:

I decided to start over with the most up to date Laravel version a couple months ago, and do my best to rewrite the entire application.

I am about 70% along, I have removed features that are just fluff, I am trying to extract others out to packages along the way (see rappasoft/lockout) and just overall try to make it less opinionated.

Also, against my better judgement I also added Socialite back in.

There's no code you can look at yet, as I have it all locally in git.

Here are some screenshots.

<img width="1792" alt="Screen Shot 2020-03-02 at 08 07 25" src="https://user-images.githubusercontent.com/6026504/75679137-0db68200-5c5d-11ea-833d-8d0de2ab2a3c.png">
<img width="1792" alt="Screen Shot 2020-03-02 at 08 07 34" src="https://user-images.githubusercontent.com/6026504/75679140-0e4f1880-5c5d-11ea-97c2-defc3eb979a6.png">
<img width="1792" alt="Screen Shot 2020-03-02 at 08 07 54" src="https://user-images.githubusercontent.com/6026504/75679141-0e4f1880-5c5d-11ea-9081-33e455d4a90a.png">

**Comment by redactuk** [comment]
Exiting news! Curious: are you sticking with repository pattern?

**Comment by rappasoft** [comment]
@redactuk  As of right now I am but it's a little lighter. But i'm open to other more modern suggestions.

**Comment by coderkoala** [comment]
@rappasoft any chance Livewire could make it in? Would it cause any conflicts? I believe it'd be a great addition, as I've anecdotally felt development time frame fall when I tried it out.

**Comment by rappasoft** [comment]
@coderkoala i'm not sure, i'm trying to not be opinionated by adding other things, if anything i've removed things. But I agree it's really nice and useful and I think it will become even more popular within the community as Vue has.

**Comment by bryanrscott** [comment]
The easy setup and structure of the project is why we chose this template.   Including the social login configured out of the box makes it much easier to use. 

Having updated manually with each major release of the boilerplate I welcome the use of packages as they might make this maintenance part easier.

Things I would like
- improve upon the features you do provide out of the box (eg search/filtering/pagination of user admin)
- a sample mobile client (eg ionic) that can connect to

**Comment by coderkoala** [comment]
>     * improve upon the features you do provide out of the box (eg search/filtering/pagination of user admin)

I tend to utilize Yajra's datatable along with datatable library, as it's pretty agnostic in the frontend. Although it'd add a bit of bloat, I feel having it would be quite useful, given as it's insanely customizable, and can apply everywhere.

**Comment by gmgarrison** [comment]
In case you're interested in comparing notes (and aren't already familiar with it), I've used this a few times: https://github.com/jeremykenedy/laravel-auth. Not implying that it should be copied but it can often be helpful to just compare with another perspective. In any case, I'm planning on using your next release for my next side project. :)

**Comment by poseso** [comment]
+1 for Yajra's DataTables

**Comment by rappasoft** [comment]
Playing with the Datatables HTML builder classes and they work really nice. I have a feeling it'll make its way in.

**Comment by chrisdan** [comment]
@rappasoft 
Please consider the following while doing the rewrite:
- revert to AdminLTE (instead of CoreUI).
- write all js (where possible atm) in vanilla js (bootstrap v5 will drop jQuery dependency completely)
- avoid using packages/ libraries that depend on jQuery

Nothing wrong with jQuery, per se, just people are moving on...

**Comment by rappasoft** [comment]
@chrisdan 

- I already have CoreUI 3 going. Why do you prefer AdminLTE?
- I'm going to keep jquery with the project for now since it is still used with the default Laravel/ui package.

I almost want to go full Vue, but I don't want to handcuff the people that want to use it with other frameworks.

But I agree jquery is being phased out.

**Comment by chrisdan** [comment]
@rappasoft 
- Previous versions of **laravel-boilerplate** used to have **AdminLTE** which i (think) is a more 'pure' open source project. Nothing wrong with freemium model. Absolutely nothing. Currently i am also using CoreUI.
- Maybe i misstated what i meant. I am not saying to drop jQuery support now (which is hard due to the fact that bootstrap requires it). What i am saying is to prefer vanilla js where possible, so to make easier the move to bootstrap 5 (whenever that is).

Also, i agree about Vue, mainly because that would mean you lose SEO-ability and also need to have SSR in place.

**Comment by neapolis79** [comment]
@rappasoft 

- I also suggest to switch to a full free **AdminLTE** 
- For permissions and role management, I would suggest switching to the https://github.com/santigarcor/laratrust library which also handles permissions and roles based on groups/teams, because the spatie library does not yet have this functionality,

**Comment by redactuk** [comment]
+1 for laratrust

**Comment by rappasoft** [comment]
OK so 2 things:

1. I already implemented CoreUI 3
2. I already implemented spatie/permission with custom grouping (not teams though)

Why do you guys prefer AdminLTE over CoreUI?

<img width="1481" alt="Screen Shot 2020-03-16 at 08 04 17" src="https://user-images.githubusercontent.com/6026504/76756798-cb149f80-675c-11ea-979d-026687086ea5.png">

**Comment by chrisdan** [comment]
@rappasoft 

>Why do you guys prefer AdminLTE over CoreUI?

Minor things that add up. For example, for the [collapse element](https://coreui.io/docs/components/bootstrap/collapse/), they seem to have overriden events and instead of the classic `show.bs.collapse` event, you need to listen/ attach to `show.coreui.collapse`. What happens if you have a shared view component (a partial) that has a collapsible element and gets shared between frontend (vanilla bootstrap) and backend (coreui)?
You now need to listen for both events in order to serve both ends...

**Comment by rabol** [comment]
Sorry to poke the bear... are there any ETA ? :)

**Comment by rappasoft** [comment]
Things have been kind of hectic lately. But i've been working on a package that will speed it up and remove the need for jquery datatables. I have it private for now but once i'm happy with an alpha i'll ket people start helping me with it.

**Comment by rabol** [comment]
Please count me in as alpha as I'm about to start a new 'project' - thanks

**Comment by rappasoft** [comment]
The BP itself still needs a lot of work, but this plugin will speed up the backend at least.

**Comment by rabol** [comment]
I'll be happy to pitch in on the BP work

**Comment by rappasoft** [comment]
Yeah I have it all local but Ill probably throw it up on a branch soon. I'm going to make this package public soon enough as well.

**Comment by rappasoft** [comment]
This is what i've been working on: https://github.com/rappasoft/laravel-livewire-tables

**Comment by audiem13** [comment]
For us who aren't great at this stuff. A document showing how to upgrade an existing basic app to the new version would be great if there is any major breaking changes.

**Comment by rappasoft** [comment]
It's a ground up completely different rebuild, there will be no upgrade. It would be use the new version with your next project. That's the unfortunate truth when using a starter project that's not a package. Though I have extracted a couple packages out already to make that easier in the future.

**Comment by mrdionjr** [comment]
Thanks for the great work! I'm available for help.

**Comment by rappasoft** [comment]
Update: Progress going slow but steady due to me writing the entire thing from scratch and having trouble deciding how I want to do things. I do have data tables implemented with Livewire using a new package I wrote. I also have converted a lot of the backend to blade components. The big internal conflict I have right now is to keep coreui/bootstrap in general, or to switch to something less invasive like tailwind. 

Going to close this for now as I won't have anything to add for a little bit.
