### ISSUE TITLE
Font-Awesome

### ISSUE THREAD

**Issue by warmwhisky** [rappasoft/laravel-boilerplate#1325]
I installed Laravel Boilerplate (Current: Laravel 6.*) yesterday. I cannot get font awesome to work. 

The classes show up in phpstorm as I type, but I always get a blank square in place of the icon.

I have tried using npm to reinstall. I can see font awesome in the frontend.js file, but they still do not show.

I have tried doing this manually by putting font awesome all.min.css file in my head and putting the webfonts in the public directory. But still no icons. 

I believe it is something to do with my lack of understanding of webpack or npm installations.

How do I disable font awesome from being put into frontend.js after I have `npm run dev`? so that my manual version  might work?

**Comment by Shuyinsama** [comment]
I am assuming you are import/referencing the `all.css `or `all.js `file that comes with font-awesome.

It's been a while since I've used this project and added font-awesome but you it sounds like you do not have the correct font-files loaded. You can either import the correct files in the frontend or use a build system like laravel mix to bundle/package the needed assets.

Without further examples/info/code there is not much we can help you with. The docs for font-awesome should have all the information you need.

**Comment by poseso** [comment]
In my case I use another template and I just had to change in my webpack file:

.setResourceRoot('../') // Turns assets paths in css relative to css file

with 

.setResourceRoot('/') // Turns assets paths in css relative to css file
