### ISSUE TITLE
Socialite Login

### ISSUE THREAD

**Issue by dhonxean** [rappasoft/laravel-boilerplate#1443]
# Before you create an issue make sure that:
- Your issue is **strictly related to the boilerplate** itself. Questions about Laravel in general belongs to the [laravel](http://laravel.io/forum) or [laracasts](https://laracasts.com/discuss/) forums.
- You have read the [documentation](https://laravel-boilerplate.com) thoroughly.
- You have searched for a similar issue among all the former issues (even closed ones).
- You have tried to replicate the issue with a clean install of the project.

# Be explicit
Try to be as explicit as you can when you ask anything.

Hello. Thank you for this wonderful template. I have a problem with socialite login. I've set it up correctly according to the docs of socialite but it returns an error of Invalid State. After an authentication it returns an error 500. 

I hope you can help me. Thank you.

Here are the snippets of my errors: 

![Screen Shot 2020-09-01 at 10 17 37 pm](https://user-images.githubusercontent.com/31211845/91862826-053d1380-eca1-11ea-823b-03bf1794d11d.png)
 errors: 

![Screen Shot 2020-09-01 at 10 15 17 pm](https://user-images.githubusercontent.com/31211845/91863115-56e59e00-eca1-11ea-8b54-e9d82df0083b.png)

**Comment by rappasoft** [comment]
Not sure what the issue is with your specific application. I've tested with all of the providers in the example env file. There is a chance something has changed since then, so if you figure that out feel free to make a PR to fix. A quick google search shows you're not alone with this error. Maybe this will help: https://stackoverflow.com/questions/30660847/laravel-socialite-invalidstateexception
