### ISSUE TITLE
What is the best practice for editor role?

### ISSUE THREAD

**Issue by perffy** [rappasoft/laravel-boilerplate#1478]
Hi guys,

I am wondering what will be the best practice using Laravel Boilerplate 7 for the following situation. 
My website will have three different roles: Administrator, Editor, User. 

The Editor will also use the backend website, but he will only be able to Create posts, and edit / delete only his own posts.

For the moment I have created the 3 roles. The editor role is of type 'admin', so these users can also see the backend system.

What will be the best implementation to check if some editor can edit a specific post, based on the author?

**Comment by iosiflivadaru** [comment]
So you said the "Editor" is able to CRUD their own posts. I don't understand your question... "check if some editor can edit a specific post based on author" is the author of a post another "Editor"?

**Comment by perffy** [comment]
sorry for my bad English. The "Editors" just need to CRUD their own posts.

**Comment by iosiflivadaru** [comment]
@perffy all good! no worries, I just wanted to clarify your question. Ok so the "Editors" can only CRUD and I believe they are also the "authors" of the posts right? if so that means you need a way to check if the post an "Editor" can access are only theirs!

For this you can have your route set like this:
```php
Route::get('posts/{post}/edit', 'PostController@edit')
```
Where **{post}** is the id of your post!

And in your controller have this: 
```php
public function edit($post)
{
    $post= Post::find($post);

    if (auth()->user()->id == $post->user_id)) {
        return view('backend.app.post.edit')->withPost($post);
    } else {
        return redirect()->route('admin.posts')->withFlashDanger(__('You do not have access to do that.'));
    }
}
```
What I'm doing here is check the id of whoever is logged it with the id of the user that owns that post!
