### ISSUE TITLE
Question: How to create new Role?

### ISSUE THREAD

**Issue by perffy** [rappasoft/laravel-boilerplate#1493]
Hi guys,

i have tried 2 ways to create in general a new Role, but none of them works fully.

1) New user type (editor)
- in the migrations, I change the enum to have the additional user type. 
- in all occurrences of self::TYPE_USER, I add also self::TYPE_EDITOR
- (GeneralHelper etc. )
- the problem comes when I am in the backend as Admin. If I want to change a role from User to Editor, it doesn't work. There was some error, telling me I cannot do that. That's why I have switched to the next option.

2) New user role (editor)
- there are only two user types: admin & user
- with the RoleSeeder, I create a new Role - Editor, in that case, the Editor is of a type user, but has an Editor role.
- the problem in the backend disappears, but there is another issue. In the GeneralHelper i have created a method isEditor(), which returns true if the user has that Role. I have also changed the implementation of the isUser() method to check for User Role too. Unfortunately all new registered from frontend users don't get User role, so i need to assign that...

What is the best implementation, any of these two options, but I am doing something wrong or there is another option?

**Comment by rappasoft** [comment]
Consider User and Admin as user types, not roles. Each user type can have their own set of roles and permissions, that's how I set it up. I'm not fully following what you're trying to do, however I suggest using permission strings to match abilities instead of roles, as those can not change. You can still assign roles to your users from the backend, but match on the permissions in those roles. Spatie actually [recommends this](https://spatie.be/docs/laravel-permission/v3/best-practices/roles-vs-permissions).

**Comment by perffy** [comment]
That is exactly the second implementation, that I have done. I don't want to attach permissions, because there are plenty of permissions. It will be much easier to have only roles. I was wondering if that is the right implementation because by adding more roles and not using permissions, there are some functionalities that need to be changed (functions in GeneralHelper and UserService). Anyway.
Happy Holidays :)
